# RPM Configuration Settings

paths:
  test_dir: "data/test_images"
  support_dir: "data/support_images"
  output_dir: "data/result_images"
  support_db: "data/support_db.pt"
  yolo_path: "data/weights/yolo/best-obb.pt"
  weights_dir: "data/weights"

models:
  yolo_conf: 0.25
  top_k: 5
  dino_thresh: 0.65
  lg_norm_thresh: 0.2
  lg_min_inliers: 30
  batch_size: 1

# Device configuration (Switch to 'cpu' if you get OOM on laptop)
devices:
  yolo: "cuda"
  dino: "cuda"      # DINO is very heavy, moving to CPU saves ~2GB VRAM
  lg: "cuda" # ONNX models on CPU are stable for demo
  
matching:
  alpha: 0.2
  beta: 0.8
  dino_high_conf_threshold: 0.8
  skip_lg_inliers_value: 999
